const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'SIGNIN_FAILURE',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION'
};
 export default userActionTypes;
